name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@v3
        with:
          version_regex: "^[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+$"
          prerelease_regex: "^[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+-\\w+$"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
